import { type NextPage } from "next";
import Head from "next/head";
import { FormGroup } from "~/component/FormGroup";
import { Input } from "~/component/Input";

const GeneratePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form className="flex flex-col gap-4" action="">
          <FormGroup>
            <label htmlFor="">Prompt</label>
            <Input />
          </FormGroup>
          <button className="rounded bg-blue-400 px-4 py-2 hover:bg-blue-500">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
